/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftLoanVaultSol from "./NFTLoanVault.sol";
export type { nftLoanVaultSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mocks from "./mocks";
export type { mocks };
export type { NFTFinder } from "./NFTFinder";
export type { NFTPool } from "./NFTPool";
export type { NFTShort } from "./NFTShort";
export type { SimpleToken } from "./SimpleToken";
