/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AMLAdapter__factory } from "./AMLAdapter__factory";
export { HRAdapter__factory } from "./HRAdapter__factory";
