export { default as Landing } from './Landing'
export { default as Dashboard } from './Dashboard'
export { default as Collections } from './Collections'
export { default as Gallery } from './Gallery'
export { default as Market } from './Market'
export { default as MyNfts } from './MyNfts'
export { default as Nft } from './Nft'
